### ISSUE TITLE
failed to export a model without vb1 file.

### ISSUE THREAD

**Issue by josh6688** [Petrascyll/gui_collect#1]
i'm trying to export a LOD model for JK students at far distance. the process failed to find a vb1 file and aborted.
i checked the structure of its vb0 file. seems like TEXCOORD2 and TEXCOORD3 section take the function of BLENDINDICES and BLENDWEIGHTS.
could you please support this format?
```
Traceback (most recent call last):
  File "E:\Anaconda3\envs\py39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "E:\360Downloads\3dmigoto-GIMI-for-playing-mods2\gui_collect-master\gui\extract_form.py", line 46, in <lambda>
    zzz.bind('<Button-1>', lambda _: self.start_extraction())
  File "E:\360Downloads\3dmigoto-GIMI-for-playing-mods2\gui_collect-master\gui\extract_form.py", line 81, in start_extraction
    extracted_components = frame_analysis.extract(path, ib_hashes, component_names)
  File "E:\360Downloads\3dmigoto-GIMI-for-playing-mods2\gui_collect-master\frame_analysis\frame_analysis.py", line 80, in extract
    set_relevant_data(components, files)
  File "E:\360Downloads\3dmigoto-GIMI-for-playing-mods2\gui_collect-master\frame_analysis\frame_analysis.py", line 279, in set_relevant_data
    print('\t\tBackup texcoord data file path: ' + texcoord_vb_path.name)
AttributeError: 'NoneType' object has no attribute 'name'
```
relevant frame dump files are attached here. the ib hash is 2ad9e5af.
[FrameAnalysis-2024-07-22-224103.zip](https://github.com/user-attachments/files/16336009/FrameAnalysis-2024-07-22-224103.zip)

**Comment by Petrascyll** [comment]
Should be fixed now by latest commit hopefully. Try downloading the latest version and dumping again please.
